update readme
atolye15/cra-recipe pull request #16
Opened 2019-11-29 08:43 UTC by ihsan-ofluoglu

2019-11-29 08:50 UTC, hsnaydd requested changes

2019-11-29 08:50 UTC, hsnaydd commented on README.md
>  After that, you may need to add types.
this line should also be deleted

2019-12-02 07:48 UTC, ihsan-ofluoglu commented on README.md
```suggestion
```

2019-12-02 07:48 UTC, hsnaydd approved these changes

2020-02-12 12:48 UTC, EricMcRay approved these changes

2020-02-12 12:48 UTC, merged